
spring:
    output:
        ansi:
            enabled: always # make colorful
    h2:
        console:
            enabled: true
    thymeleaf:
        cache: false

    servlet:
        multipart:
            max-file-size: -1
            max-request-size: -1
             


    datasource:
        url: jdbc:h2:tcp://localhost/~/shoppingmall/db        
        username: sa
        password: 
        driver-class-name: org.h2.Driver

    jpa: 
        generate-ddl: true
        hibernate:
            ddl-auto : update
        properties: 
            hibernate:
                default_batch_fetch_size: 1000 
                format_sql : TRUE            

logging:
    level:        
        org.hibernate.SQL: debug   #using loger recommend using this not show_sql
        org.springframework.security: warn   